name: Philip Rowe Designs
favicon: null
layout_spectrum: 0.7109195636585355
typography_spectrum: 0.5646713357418776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.35370688373222947
  lightness: 0.29435576614923775
  saturation: 0.6107415831647813
  rhythmicContrast: 0.006770687876269221
purpose: []
